const REQUEST_CREATE_TOPIC = 'REQUEST_CREATE_TOPIC';
const ERROR_CREATE_TOPIC = 'ERROR_CREATE_TOPIC';
const SUCCESS_CREATE_TOPIC = 'SUCCESS_CREATE_TOPIC';
const REQUEST_GET_CATEGORY = 'REQUEST_GET_CATEGORY';
const ERROR_GET_CATEGORY = 'ERROR_GET_CATEGORY';
const SUCCESS_GET_CATEGORY = 'SUCCESS_GET_CATEGORY';

export {
	REQUEST_CREATE_TOPIC,
	SUCCESS_CREATE_TOPIC,
	ERROR_CREATE_TOPIC,
	REQUEST_GET_CATEGORY,
	SUCCESS_GET_CATEGORY,
	ERROR_GET_CATEGORY,
};
